uart_device: /dev/serial0
baudrate: 115200

topics:
  rtc: "spotter/utc-time"
  # add more as you grow:
  led: "camera/led"      # optional example

led:
  pin: 17                # BCM pin for the example LED handler

clock:
  enabled: true
  apply_if_drift_seconds: 0.3     # was 2
  min_apply_interval_seconds: 300 # keep this to avoid thrashing
  max_backward_seconds: 0
  apply_immediately_on_boot: true
