uart_device: /dev/serial0
baudrate: 115200

topics:
  rtc: "spotter/utc-time"
  test_pi: test/pi
  camera_capture_image: camera/capture/image
  camera_capture_video: camera/capture/video

clock:
  enabled: true
  max_backward_seconds: 0        # 0 = never move backwards
  apply_if_drift_seconds: 1      # only step if |drift| > 2s
  min_apply_interval_seconds: 11  # at most once every 5 min
  
paths:
  data_root: "/home/pi/bm_camera/camera_software"   # or "~/.local/share/bm_camera"
  images: "images"
  videos: "videos"
  buffer: "buffer"